id: test1
name: Webhook example using bash script
script: /home/alampare/repos/perforator/src/main/resources/jobs/example/example1/run.sh
result: /tmp/result.json
artifacts:
  perf_stat: /tmp/perf-stat.txt
  report_html: /tmp/report.html
  result: /tmp/result.json
